// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package repository

import (
	"context"
)

type Querier interface {
	CreatePrivilege(ctx context.Context, username string) (Privilege, error)
	CreatePrivilegeHistory(ctx context.Context, arg CreatePrivilegeHistoryParams) (PrivilegeHistory, error)
	GetPrivilege(ctx context.Context, username string) (Privilege, error)
	ListPrivilegeHistories(ctx context.Context, privilegeID int32) ([]PrivilegeHistory, error)
	UpdatePrivilegeBalance(ctx context.Context, arg UpdatePrivilegeBalanceParams) error
}

var _ Querier = (*Queries)(nil)
